### PR TITLE
Desktop version

### PR DESCRIPTION
**Pull request by Maedea9**
I modified the whole project using media queries for the desktop version of the portfolio figma template 5 as required by the Microverse assignment. I added additional images in SVG format and worked on transitions and animations through the different sections to make the project more visually engaging. Although the works/projects section was extremely challenging and I'm quite satisfied with the result, I will improve it. 😅 Let me know what you think!

### CODE REVIEW

**Review by zieeco — CHANGES_REQUESTED** [review]
Hi @Maedea9,


You've done an impressive job with the desktop design 👏 
You've done well, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- Impressive design approach :100: 
- No linter errors.✔️
- Nice UI/UX on the desktop version. ✔️
- Descriptive PR. ✔️


## Required Changes ♻️
_Check the comments below._


- [ ] Your design looks great on the desktop version, however, it has a horizontal scroll in the mobile version, which has made your mobile design not user-friendly. Please, see the demo video to see the mobile design in action to fix the issue.

*horizontal scroll in mobile version*

[Screencast from 02-25-2023 12:50:11 AM.webm](https://user-images.githubusercontent.com/59397159/221322497-78ec1759-c043-4f6c-a6ff-b1de2da3a3ce.webm)




## Optional suggestions
- N/A

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Maedea9** [comment]
@zieeco thank you for your comments and your suggestion! I wonder what could be wrong because I even tried it with the netlify app on my phone and my boyfriend's phone which is a bit bigger and it seems good. 
[https://mcportfoliolivedemo.netlify.app/](url)
I checked maybe it could be the overflow: hidden property I used in the body? I just disabled it and tried it again. Hope it's solved! 👍

**Review by amon-cofie — CHANGES_REQUESTED** [review]
Hi @Maedea9 , 

Great work so far👏 
You've done well, but there are still some issues which aren't addressed yet.



 ## Highlights

- Impressive design approach ✔️
- No linter errors.✔️
- Nice UI/UX on the desktop version. ✔️
- Descriptive PR. ✔️

 ## Required Changes ♻️

Unfortunately, the observed bug by the previous reviewer still persists. I suggest you take a closer look at the styles in the mobile version as I suspect that the issue could be a property in the mobile version styles that still persists but is unwanted in the desktop version styles


_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Maedea9** [comment]
Thank you @amon-cofie for telling me this! It seems to be that when I was resolving some conflicts in my branches, some of the final code was overwritten by error, but it seems to be fixed now. I've attached a video as well. Thank you! I sincerely hope you see this as well on your screens because this is my last review request! I'm so nervous.

https://user-images.githubusercontent.com/120128067/221329982-19e9326d-d911-4923-bd79-982bc196d3f9.mp4

**Review by NduatiKagiri — APPROVED** [review]
Hi @Maedea9 👋 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

ea0cb5a48e3337523ffe8d60f177879d

## Highlights ✔️ 
✅ No Linters errors
✅ GitHub Flow observed

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Maedea9** [comment]
@NduatiKagiri Thank you!!! I'm so happy! Template 5 was very hard but I learned so much!

**Pull request merged**
